#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Robson Trasel
"""Generates crates/keyhammer/src/text/tables.rs from Python's unicodedata.

Usage: python crates/keyhammer/scripts/gen_text_tables.py > crates/keyhammer/src/text/tables.rs

The tables cover U+00C0..=U+017F (the letters of Latin-1 Supplement and all of
Latin Extended-A). See docs/design/unicode.md, section 2, for the policy.
"""

import sys
import unicodedata as ud

FIRST, LAST = 0xC0, 0x17F

# Letters whose NFKD decomposition without combining marks is not ASCII:
# fixed choices (docs/design/unicode.md, section 2.2).
SPECIAL_BASE = {
    "Æ": "AE", "æ": "ae", "Œ": "OE", "œ": "oe", "ß": "ss",
    "Ø": "O", "ø": "o", "Đ": "D", "đ": "d", "Ħ": "H", "ħ": "h",
    "Ł": "L", "ł": "l", "Ŧ": "T", "ŧ": "t", "Ð": "D", "ð": "d",
    "Þ": "TH", "þ": "th", "ı": "i", "Ŀ": "L", "ŀ": "l", "ĸ": "q",
    "Ŋ": "N", "ŋ": "n", "ŉ": "'n",
}

# Full case foldings that are more than one character: handled in code.
MULTI_FOLD = {"ß", "İ", "ŉ"}


def base(c):
    if c in SPECIAL_BASE:
        return SPECIAL_BASE[c]
    if not ud.category(c).startswith("L"):
        return None
    d = "".join(x for x in ud.normalize("NFKD", c) if not ud.combining(x))
    assert d.isascii() and d.isalpha(), (hex(ord(c)), d)
    return None if d == c else d


def fold(c):
    f = c.casefold()
    if c in MULTI_FOLD:
        assert len(f) == 2, hex(ord(c))
        return c
    assert len(f) == 1, hex(ord(c))
    return f


def byte_lit(x):
    if x == 0:
        return "0"
    if chr(x) == "'":
        return "b'\\''"
    return "b'" + chr(x) + "'"


def main():
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    out = sys.stdout
    out.write("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
    out.write("// Copyright (C) 2026 Robson Trasel\n\n")
    out.write(
        "//! Generated by `scripts/gen_text_tables.py` from Unicode "
        + ud.unidata_version
        + " (Python `unicodedata`). Do not edit.\n\n"
    )
    out.write("/// First code point covered by the tables.\n")
    out.write(f"pub(super) const FIRST: u32 = 0x{FIRST:X};\n")
    out.write("/// Last code point covered by the tables.\n")
    out.write(f"pub(super) const LAST: u32 = 0x{LAST:X};\n\n")

    out.write(
        "/// Simple case folding of U+00C0..=U+017F (the code point itself when\n"
        "/// unchanged). The multi-character foldings of U+00DF, U+0130 and U+0149\n"
        "/// are left out (identity here) and handled in code.\n"
    )
    out.write("#[rustfmt::skip]\n")
    out.write(f"pub(super) const CASE_FOLD: [u16; {LAST - FIRST + 1}] = [\n")
    for row in range(FIRST, LAST + 1, 8):
        cells = []
        for cp in range(row, min(row + 8, LAST + 1)):
            cells.append(f"0x{ord(fold(chr(cp))):04X}")
        out.write("    " + ", ".join(cells) + ",\n")
    out.write("];\n\n")

    out.write(
        "/// Base letters of U+00C0..=U+017F without diacritics: up to two ASCII\n"
        "/// bytes, `[0, 0]` when the character is unchanged.\n"
    )
    out.write("#[rustfmt::skip]\n")
    out.write(f"pub(super) const BASE: [[u8; 2]; {LAST - FIRST + 1}] = [\n")
    for row in range(FIRST, LAST + 1, 8):
        cells = []
        for cp in range(row, min(row + 8, LAST + 1)):
            b = base(chr(cp))
            if b is None:
                cells.append("[0, 0]")
            else:
                assert 1 <= len(b) <= 2 and b.isascii() and '"' not in b
                if len(b) == 2:
                    cells.append('*b"' + b + '"')
                else:
                    cells.append("[" + byte_lit(ord(b)) + ", 0]")
        out.write("    " + ", ".join(cells) + ",\n")
    out.write("];\n")


if __name__ == "__main__":
    main()
