[package]
name = "keyhammer-node"
version = "0.1.0"
license = "AGPL-3.0-or-later"
publish = false
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
keyhammer = { package = "keyhammer-legacy", path = "../../legacy" }
napi = { version = "3", features = ["default"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
