/* SPDX-License-Identifier: AGPL-3.0-or-later */
/* Copyright (C) 2026 Robson Trasel */
/* GENERATED by cbindgen from bindings/c/src/lib.rs. Do not edit by hand. */

#ifndef KEYHAMMER_H
#define KEYHAMMER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 The ABI version. It changes only when an incompatible change is made; see
 `docs/design/c-abi.md`. Compare it with `kh_abi_version` at run time.
 */
#define KH_ABI_VERSION 2

/*
 `kh_config.ranking`: order by cost rounded up to whole edit units.
 */
#define KH_RANKING_COARSE 0

/*
 `kh_config.ranking`: order by the exact weighted cost.
 */
#define KH_RANKING_EXACT 1

/*
 The longest accepted query, in code points after normalisation (ABI
 version 1 counted bytes; see `docs/design/c-abi.md`).
 */
#define KH_MAX_QUERY_LEN 128

/*
 The longest accepted query, in UTF-8 bytes: 4 bytes for each of
 `KH_MAX_QUERY_LEN` code points. Longer input is refused before it is read.
 */
#define KH_MAX_QUERY_BYTES (4 * KH_MAX_QUERY_LEN)

/*
 `kh_index_build_ex` flag: do not fold case (`A` and `a` differ).
 */
#define KH_NORM_KEEP_CASE 1

/*
 `kh_index_build_ex` flag: do not fold diacritics (`é` and `e` differ).
 */
#define KH_NORM_KEEP_DIACRITICS 2

/*
 Result of a call. `KH_OK` is 0; every failure is non-zero. New codes may
 be added in later minor versions, so treat unknown non-zero values as
 failures.
 */
typedef enum kh_status {
  /*
   Success.
   */
  KH_OK = 0,
  /*
   A required pointer argument was null.
   */
  KH_ERR_NULL_POINTER = 1,
  /*
   A length does not fit (larger than `isize::MAX`, or more entries than
   an index can hold).
   */
  KH_ERR_INVALID_LENGTH = 2,
  /*
   A term or query is not valid UTF-8.
   */
  KH_ERR_INVALID_UTF8 = 3,
  /*
   An argument has an invalid value (unknown ranking, budget too large,
   `struct_size` too small).
   */
  KH_ERR_INVALID_ARGUMENT = 4,
  /*
   The entry array is empty.
   */
  KH_ERR_EMPTY_INDEX = 5,
  /*
   A term is empty.
   */
  KH_ERR_EMPTY_TERM = 6,
  /*
   A term is longer than 65535 bytes.
   */
  KH_ERR_TERM_TOO_LONG = 7,
  /*
   The query is longer than `KH_MAX_QUERY_LEN` code points after
   normalisation, or than `KH_MAX_QUERY_BYTES` bytes.
   */
  KH_ERR_QUERY_TOO_LONG = 8,
  /*
   An internal error (a caught panic). The message is in `kh_last_error`.
   */
  KH_ERR_INTERNAL = 9,
} kh_status;

/*
 An opaque index handle. Create it with `kh_index_build`, free it with
 `kh_index_free`.
 */
typedef struct kh_index kh_index;

/*
 Search parameters. Call `kh_config_default` to fill it, then change
 fields. `struct_size` must be `sizeof(kh_config)` as seen by the caller;
 it lets a library newer than the header still read this struct.
 */
typedef struct kh_config {
  /*
   `sizeof(kh_config)` of the header the caller was compiled with.
   */
  uint32_t struct_size;
  /*
   Number of results wanted (default 10; 0 returns no hits).
   */
  uint32_t k;
  /*
   Largest accepted edit cost, fixed point with 16 = one ordinary edit
   (default 32; at most 64, else `KH_ERR_INVALID_ARGUMENT`).
   */
  uint32_t budget;
  /*
   `KH_RANKING_COARSE` (default) or `KH_RANKING_EXACT`.
   */
  uint32_t ranking;
  /*
   Hard limit on expanded trie nodes (default 100000); the search stops
   early and reports `truncated` when it is reached.
   */
  uint64_t max_nodes;
  /*
   Non-zero enables the subtree-signature lower bound (does not change
   the results). Default 0.
   */
  uint32_t tsb;
  /*
   Must be 0. It makes `sizeof(kh_config)` identical on all targets (no
   implicit tail padding), so that appended fields grow the struct.
   */
  uint32_t reserved;
} kh_config;

/*
 One dictionary entry given to `kh_index_build`.
 */
typedef struct kh_entry {
  /*
   The term: `len` bytes of UTF-8, not NUL-terminated.
   */
  const uint8_t *term;
  /*
   Length of the term in bytes (1 to 65535).
   */
  size_t len;
  /*
   The term's weight (higher ranks first among equal costs).
   */
  uint16_t weight;
} kh_entry;

/*
 One search hit. `term` points into the index and stays valid until the
 index is freed; it is not NUL-terminated.
 */
typedef struct kh_hit {
  /*
   The matched term as it was given to `kh_index_build`, `term_len` bytes
   of UTF-8 (original case and accents, not the normalised form).
   For terms merged by normalisation, the entry that was kept.
   */
  const uint8_t *term;
  /*
   Length of `term` in bytes.
   */
  size_t term_len;
  /*
   Term id inside the index (position in the byte-sorted, deduplicated
   list of normalised terms).
   */
  uint32_t id;
  /*
   Exact weighted edit cost (16 = one ordinary edit), whatever the ranking.
   */
  uint32_t cost;
  /*
   The term's weight.
   */
  uint32_t weight;
  /*
   Position in the `kh_entry` array given to `kh_index_build` of the
   entry this hit is (the one kept among terms equal after
   normalisation).
   */
  uint32_t input_index;
} kh_hit;

/*
 The output of `kh_search`. Free it with `kh_results_free`.
 */
typedef struct kh_results {
  /*
   `len` hits, best first; null when `len` is 0.
   */
  struct kh_hit *hits;
  /*
   Number of hits.
   */
  size_t len;
  /*
   Trie nodes expanded by the search.
   */
  uint64_t nodes_expanded;
  /*
   Non-zero if `max_nodes` stopped the search early.
   */
  uint32_t truncated;
} kh_results;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns `KH_ABI_VERSION` of the loaded library. A wrapper should check
 that it equals the version of the header it was built against.
 */
uint32_t kh_abi_version(void);

/*
 The message of the last failed call on the calling thread, as a
 NUL-terminated UTF-8 string; empty if the last call succeeded. The pointer
 is valid until the next call into this library on the same thread. Never
 null.
 */
const char *kh_last_error(void);

/*
 A static, NUL-terminated description of a status code. Any integer is
 accepted (it is not an enum on purpose: a value outside the enum is
 undefined behaviour in Rust); unknown codes give "unknown status". Never
 null.
 */
const char *kh_status_string(int32_t status);

/*
 Fills `cfg` with the defaults (`k = 10`, `budget = 32`, coarse ranking,
 `max_nodes = 100000`, `tsb = 0`) and sets `struct_size`.

 # Safety

 `cfg` must be null or valid for writing a `kh_config`.
 */
enum kh_status kh_config_default(struct kh_config *cfg);

/*
 Builds an index from `n` entries and stores the handle in `*out`.

 Terms are normalised (case and diacritics folded, as `kh_index_build_ex`
 with no flags); terms equal after normalisation are merged, keeping the
 highest weight (then the first). Hits return the term as given. On success `*out` is a new handle that must be released with
 `kh_index_free`; on failure `*out` is set to null. The entries and their
 term bytes are copied and need not outlive the call. Embedded NUL bytes in
 a term are accepted and returned unchanged (terms are not C strings).

 Fails with `KH_ERR_NULL_POINTER` (`out` or `entries` null, or a term
 pointer null with a non-zero length), `KH_ERR_INVALID_LENGTH`,
 `KH_ERR_EMPTY_INDEX` (`n == 0`), `KH_ERR_EMPTY_TERM`,
 `KH_ERR_TERM_TOO_LONG` or `KH_ERR_INVALID_UTF8`. A term that normalises to
 nothing (only combining marks) fails with `KH_ERR_EMPTY_TERM`, and one that
 normalises to more than 65535 bytes with `KH_ERR_TERM_TOO_LONG`.

 # Safety

 `out` must be null or valid for writing a pointer. `entries` must be null
 (only with `n == 0`) or point to `n` initialised `kh_entry`, each of
 whose `term` is null (only with `len == 0`) or points to `len` initialised
 bytes.
 */
enum kh_status kh_index_build(const struct kh_entry *entries,
                              size_t n,
                              struct kh_index **out);

/*
 `kh_index_build` with normalisation flags: 0 folds case and diacritics (the
 default), `KH_NORM_KEEP_CASE` and `KH_NORM_KEEP_DIACRITICS` (ORed) turn a
 folding off. Queries are normalised the same way as the terms. Any other
 bit fails with `KH_ERR_INVALID_ARGUMENT`; the other failures are those of
 `kh_index_build`.

 # Safety

 As `kh_index_build`.
 */
enum kh_status kh_index_build_ex(const struct kh_entry *entries,
                                 size_t n,
                                 uint32_t flags,
                                 struct kh_index **out);

/*
 Frees an index and sets `*index` to null, so that freeing the same
 variable twice is a no-op. A null `index` or `*index` is ignored. Hits
 (their `term` pointers) obtained from this index must not be used after
 this call; a `kh_results` itself stays valid and must still be freed.

 # Safety

 `index` must be null or point to a pointer that is null or came from
 `kh_index_build` and has not been freed through any other copy. No other
 thread may be using the index.
 */
void kh_index_free(struct kh_index **index);

/*
 Stores the number of distinct terms of the index in `*out`.

 # Safety

 `index` must be null or a live handle; `out` must be null or valid for
 writing a `size_t`.
 */
enum kh_status kh_index_len(const struct kh_index *index, size_t *out);

/*
 Searches `index` for the UTF-8 query `(query, query_len)` and fills `*out`.

 `cfg` may be null for the defaults. `*out` is fully overwritten (it is not
 read, so an uninitialised struct is fine, but a previous result in it is
 leaked unless freed first); on failure it is set to an empty result. On
 success release it with `kh_results_free`. The query is normalised like
 the terms (`ACAO` finds `ação`). An empty query is allowed. Embedded NUL bytes are ordinary
 bytes. The pointer returned by `kh_last_error` is invalidated by the next
 call into the library, including `kh_index_free` and `kh_results_free`.
 Copying a `kh_results` and freeing both copies is a double free, like
 copying the handle.

 Fails with `KH_ERR_NULL_POINTER` (`index` or `out` null, or `query` null
 with a non-zero length), `KH_ERR_INVALID_UTF8`,
 `KH_ERR_QUERY_TOO_LONG` (`query_len` above `KH_MAX_QUERY_BYTES`, checked
 before the buffer is read, so a huge length is reported this way and
 `KH_ERR_INVALID_LENGTH` is never returned by this function; or more than
 `KH_MAX_QUERY_LEN` code points after normalisation) or
 `KH_ERR_INVALID_ARGUMENT` (bad `cfg`, including `reserved != 0`).

 # Safety

 `index` must be null or a live handle. `query` must be null (only with
 `query_len == 0`) or point to `query_len` initialised bytes. `cfg` must be
 null or point to `cfg->struct_size` readable bytes. `out` must be null or
 valid for writing a `kh_results`.
 */
enum kh_status kh_search(const struct kh_index *index,
                         const uint8_t *query,
                         size_t query_len,
                         const struct kh_config *cfg,
                         struct kh_results *out);

/*
 Frees the hits of a `kh_results` and resets it to the empty result, so
 that freeing it twice is a no-op. Null and empty results are ignored.

 # Safety

 `results` must be null or point to a `kh_results` that was filled by
 `kh_search` (or zero-initialised) and not modified by the caller.
 */
void kh_results_free(struct kh_results *results);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KEYHAMMER_H */
