// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Robson Trasel

//! Generated by `scripts/gen_text_tables.py` from Unicode 15.0.0 (Python `unicodedata`). Do not edit.

/// First code point covered by the tables.
pub(super) const FIRST: u32 = 0xC0;
/// Last code point covered by the tables.
pub(super) const LAST: u32 = 0x17F;

/// Simple case folding of U+00C0..=U+017F (the code point itself when
/// unchanged). The multi-character foldings of U+00DF, U+0130 and U+0149
/// are left out (identity here) and handled in code.
#[rustfmt::skip]
pub(super) const CASE_FOLD: [u16; 192] = [
    0x00E0, 0x00E1, 0x00E2, 0x00E3, 0x00E4, 0x00E5, 0x00E6, 0x00E7,
    0x00E8, 0x00E9, 0x00EA, 0x00EB, 0x00EC, 0x00ED, 0x00EE, 0x00EF,
    0x00F0, 0x00F1, 0x00F2, 0x00F3, 0x00F4, 0x00F5, 0x00F6, 0x00D7,
    0x00F8, 0x00F9, 0x00FA, 0x00FB, 0x00FC, 0x00FD, 0x00FE, 0x00DF,
    0x00E0, 0x00E1, 0x00E2, 0x00E3, 0x00E4, 0x00E5, 0x00E6, 0x00E7,
    0x00E8, 0x00E9, 0x00EA, 0x00EB, 0x00EC, 0x00ED, 0x00EE, 0x00EF,
    0x00F0, 0x00F1, 0x00F2, 0x00F3, 0x00F4, 0x00F5, 0x00F6, 0x00F7,
    0x00F8, 0x00F9, 0x00FA, 0x00FB, 0x00FC, 0x00FD, 0x00FE, 0x00FF,
    0x0101, 0x0101, 0x0103, 0x0103, 0x0105, 0x0105, 0x0107, 0x0107,
    0x0109, 0x0109, 0x010B, 0x010B, 0x010D, 0x010D, 0x010F, 0x010F,
    0x0111, 0x0111, 0x0113, 0x0113, 0x0115, 0x0115, 0x0117, 0x0117,
    0x0119, 0x0119, 0x011B, 0x011B, 0x011D, 0x011D, 0x011F, 0x011F,
    0x0121, 0x0121, 0x0123, 0x0123, 0x0125, 0x0125, 0x0127, 0x0127,
    0x0129, 0x0129, 0x012B, 0x012B, 0x012D, 0x012D, 0x012F, 0x012F,
    0x0130, 0x0131, 0x0133, 0x0133, 0x0135, 0x0135, 0x0137, 0x0137,
    0x0138, 0x013A, 0x013A, 0x013C, 0x013C, 0x013E, 0x013E, 0x0140,
    0x0140, 0x0142, 0x0142, 0x0144, 0x0144, 0x0146, 0x0146, 0x0148,
    0x0148, 0x0149, 0x014B, 0x014B, 0x014D, 0x014D, 0x014F, 0x014F,
    0x0151, 0x0151, 0x0153, 0x0153, 0x0155, 0x0155, 0x0157, 0x0157,
    0x0159, 0x0159, 0x015B, 0x015B, 0x015D, 0x015D, 0x015F, 0x015F,
    0x0161, 0x0161, 0x0163, 0x0163, 0x0165, 0x0165, 0x0167, 0x0167,
    0x0169, 0x0169, 0x016B, 0x016B, 0x016D, 0x016D, 0x016F, 0x016F,
    0x0171, 0x0171, 0x0173, 0x0173, 0x0175, 0x0175, 0x0177, 0x0177,
    0x00FF, 0x017A, 0x017A, 0x017C, 0x017C, 0x017E, 0x017E, 0x0073,
];

/// Base letters of U+00C0..=U+017F without diacritics: up to two ASCII
/// bytes, `[0, 0]` when the character is unchanged.
#[rustfmt::skip]
pub(super) const BASE: [[u8; 2]; 192] = [
    [b'A', 0], [b'A', 0], [b'A', 0], [b'A', 0], [b'A', 0], [b'A', 0], *b"AE", [b'C', 0],
    [b'E', 0], [b'E', 0], [b'E', 0], [b'E', 0], [b'I', 0], [b'I', 0], [b'I', 0], [b'I', 0],
    [b'D', 0], [b'N', 0], [b'O', 0], [b'O', 0], [b'O', 0], [b'O', 0], [b'O', 0], [0, 0],
    [b'O', 0], [b'U', 0], [b'U', 0], [b'U', 0], [b'U', 0], [b'Y', 0], *b"TH", *b"ss",
    [b'a', 0], [b'a', 0], [b'a', 0], [b'a', 0], [b'a', 0], [b'a', 0], *b"ae", [b'c', 0],
    [b'e', 0], [b'e', 0], [b'e', 0], [b'e', 0], [b'i', 0], [b'i', 0], [b'i', 0], [b'i', 0],
    [b'd', 0], [b'n', 0], [b'o', 0], [b'o', 0], [b'o', 0], [b'o', 0], [b'o', 0], [0, 0],
    [b'o', 0], [b'u', 0], [b'u', 0], [b'u', 0], [b'u', 0], [b'y', 0], *b"th", [b'y', 0],
    [b'A', 0], [b'a', 0], [b'A', 0], [b'a', 0], [b'A', 0], [b'a', 0], [b'C', 0], [b'c', 0],
    [b'C', 0], [b'c', 0], [b'C', 0], [b'c', 0], [b'C', 0], [b'c', 0], [b'D', 0], [b'd', 0],
    [b'D', 0], [b'd', 0], [b'E', 0], [b'e', 0], [b'E', 0], [b'e', 0], [b'E', 0], [b'e', 0],
    [b'E', 0], [b'e', 0], [b'E', 0], [b'e', 0], [b'G', 0], [b'g', 0], [b'G', 0], [b'g', 0],
    [b'G', 0], [b'g', 0], [b'G', 0], [b'g', 0], [b'H', 0], [b'h', 0], [b'H', 0], [b'h', 0],
    [b'I', 0], [b'i', 0], [b'I', 0], [b'i', 0], [b'I', 0], [b'i', 0], [b'I', 0], [b'i', 0],
    [b'I', 0], [b'i', 0], *b"IJ", *b"ij", [b'J', 0], [b'j', 0], [b'K', 0], [b'k', 0],
    [b'q', 0], [b'L', 0], [b'l', 0], [b'L', 0], [b'l', 0], [b'L', 0], [b'l', 0], [b'L', 0],
    [b'l', 0], [b'L', 0], [b'l', 0], [b'N', 0], [b'n', 0], [b'N', 0], [b'n', 0], [b'N', 0],
    [b'n', 0], *b"'n", [b'N', 0], [b'n', 0], [b'O', 0], [b'o', 0], [b'O', 0], [b'o', 0],
    [b'O', 0], [b'o', 0], *b"OE", *b"oe", [b'R', 0], [b'r', 0], [b'R', 0], [b'r', 0],
    [b'R', 0], [b'r', 0], [b'S', 0], [b's', 0], [b'S', 0], [b's', 0], [b'S', 0], [b's', 0],
    [b'S', 0], [b's', 0], [b'T', 0], [b't', 0], [b'T', 0], [b't', 0], [b'T', 0], [b't', 0],
    [b'U', 0], [b'u', 0], [b'U', 0], [b'u', 0], [b'U', 0], [b'u', 0], [b'U', 0], [b'u', 0],
    [b'U', 0], [b'u', 0], [b'U', 0], [b'u', 0], [b'W', 0], [b'w', 0], [b'Y', 0], [b'y', 0],
    [b'Y', 0], [b'Z', 0], [b'z', 0], [b'Z', 0], [b'z', 0], [b'Z', 0], [b'z', 0], [b's', 0],
];
