// @ts-check
import { themes as prismThemes } from 'prism-react-renderer';

const baseUrl = '/Keyhammer/';
// The rustdoc output is generated by CI (`cargo doc`) and copied into
// static/api/. It does not exist in a plain local `npm run build`, so it is
// linked with the `pathname://` protocol: Docusaurus then does not treat it as
// an internal route and `onBrokenLinks: 'throw'` keeps passing.
const apiHref = `pathname://${baseUrl}api/keyhammer/index.html`;

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Keyhammer',
  tagline: 'Typo-tolerant top-k search over a compact trie, with keyboard-aware edit costs',
  favicon: 'img/favicon.svg',
  url: 'https://keyhammer.github.io',
  baseUrl,
  organizationName: 'Keyhammer',
  projectName: 'Keyhammer',
  trailingSlash: false,
  onBrokenLinks: 'throw',
  // Plain .md files (CONTRIBUTING, CHANGELOG, ...) are CommonMark, so `<`, `{`
  // and `}` in them do not break the build as MDX would.
  markdown: { format: 'detect' },
  i18n: { defaultLocale: 'en', locales: ['en'] },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: './sidebars.js',
          editUrl: 'https://github.com/Keyhammer/Keyhammer/edit/main/website/',
        },
        blog: false,
        theme: { customCss: './src/css/custom.css' },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: { respectPrefersColorScheme: true },
      navbar: {
        title: 'Keyhammer',
        items: [
          { type: 'docSidebar', sidebarId: 'docs', position: 'left', label: 'Docs' },
          { href: apiHref, label: 'API reference', position: 'left' },
          { href: 'https://github.com/Keyhammer/Keyhammer', label: 'GitHub', position: 'right' },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              { label: 'Introduction', to: '/docs/introduction' },
              { label: 'Results (M0 gate)', to: '/docs/results' },
              { label: 'API reference', href: apiHref },
            ],
          },
          {
            title: 'Project',
            items: [
              { label: 'GitHub', href: 'https://github.com/Keyhammer/Keyhammer' },
              {
                label: 'License (AGPL-3.0-or-later)',
                href: 'https://github.com/Keyhammer/Keyhammer/blob/main/LICENSE',
              },
            ],
          },
        ],
        copyright: 'Keyhammer is an unpublished prototype. Documentation built with Docusaurus.',
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['rust', 'toml', 'bash'],
      },
    }),
};

export default config;
