// @ts-check
const baseUrl = '/Keyhammer/';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    'how-it-works',
    'results',
    'competitors',
    'competitors-js',
    'prior-art',
    'contributing',
    'changelog',
    // Generated by rustdoc in CI; see the note in docusaurus.config.js.
    { type: 'link', label: 'API reference', href: `pathname://${baseUrl}api/keyhammer/index.html` },
  ],
};

export default sidebars;
